workflows:
  Test-workflow:
    name: Test CI Pipeline
    scripts:
      - name: CICD Started
        script: echo "Welcome to your CICD set up"
      - name: Build CICD project
        script: xcodebuild build -workspace "ci-cd-ios-test.xcodeproj" -scheme "ci-cd-ios-test" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    publishing:
        email:
            recipients:
            - usameltmsah@gmail.com
