workflows:
  Test-workflow:
    name: Test CI Pipeline
    scripts:
      - name: CICD Started
        script: echo "Welcome to your CICD set up"
      - name: Build CICD project
        script: xcodebuild xcode-project run-tests --workspace "ci-cd-ios-test.xcworkspace" --scheme "ci-cd-ios-test" --device "iPhone 11"
    publishing:
        email:
            recipients:
            - usameltmsah@gmail.com
