workflows:
  Test-workflow:
    name: Test CI Pipeline
    scripts:
      - name: CICD Started
        script: echo "Welcome to your CICD set up"
      - name: Build CICD project
        script: |
            xcode-project run-tests \
            --workspace ci-cd-ios-test.xcworkspace \
            --scheme ci-cd-ios-test
        test_report: build/ios/test/*.xml
    publishing:
        email:
            recipients:
            - usameltmsah@gmail.com
