workflows:
  Test-workflow:
    name: Test CI Pipeline
    scripts:
      - name: CICD Started
        script: echo "Welcome to your CICD set up"
      - name: Build CICD project
        script: xcodebuild clean -project "ci-cd-ios-test.xcodeproj" -scheme "ci-cd-ios-test"
    publishing:
        email:
            recipients:
            - usameltmsah@gmail.com
